# Generated by Django 4.2.2 on 2023-07-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('books_available', models.IntegerField()),
                ('book_author', models.CharField(max_length=100)),
                ('book_link', models.CharField(max_length=100)),
                ('book_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='books_issued',
            field=models.ManyToManyField(blank=True, default=None, to='users.book'),
        ),
    ]
