# Generated by Django 4.2.1 on 2023-05-27 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Student_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=100)),
                ('Course_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('Friday_Routine', models.ManyToManyField(to='routines.friday')),
                ('Monday_Routine', models.ManyToManyField(to='routines.monday')),
                ('Sunday_Routine', models.ManyToManyField(to='routines.sunday')),
                ('Thursday_Routine', models.ManyToManyField(to='routines.thursday')),
                ('Tuesday_Routine', models.ManyToManyField(to='routines.tuesday')),
                ('Wednesday_Routine', models.ManyToManyField(to='routines.wednesday')),
            ],
        ),
    ]
