# Generated by Django 4.2.1 on 2023-05-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
