# Generated by Django 4.2.1 on 2023-05-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_teacher_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
