# Generated by Django 4.2.1 on 2023-05-27 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('Teacher_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=100)),
                ('Module_ID', models.ManyToManyField(to='modules.module')),
            ],
        ),
    ]
