# Generated by Django 4.2.2 on 2023-07-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_module_credit_hours_module_tutor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='module_description',
            field=models.CharField(max_length=1500),
        ),
    ]
