# Generated by Django 4.2.2 on 2023-06-25 05:39

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='Content',
        ),
        migrations.AddField(
            model_name='blog',
            name='HtmlContent',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
