# Generated by Django 4.2.2 on 2023-06-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('attendance', '0002_remove_attendance_student_attendance_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ManyToManyField(to='users.profile'),
        ),
    ]
